#
# package     Extly.VM
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2018-2020 Andrea Gentil - Anibal Sanchez <team@extly.com>
# license     MIT
# link        http://extly.tech
#
# WORKING WITH LAMP - https://docs.devwithlando.io/tutorials/lamp.html
#
# REQUIREMENTS: Lando 3.0.0-RC.2+ - Tested on 3.0.0-RC.17

name: $replace-with-a-name$
recipe: lamp

proxy:
  appserver:
    - $replace-with-a-name$.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '7.4'
  via: apache
  webroot: www
  xdebug: true
  config:
    php: config/php.ini

services:
  appserver:
    ports:
      # A nice http://localhost:8080
      - '8080:80'

  database:
    type: mysql
    creds:
      user: $replace-with-a-name$db
      password: $replace-with-a-name$db
      database: $replace-with-a-name$db

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    hogfrom:
      - appserver

