#
# package     Extly.VM
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2012-2020 Extly, CB <team@extly.com>
# license     MIT
# link        https://extly.com
#
# WORKING WITH LARAVEL - https://docs.lando.dev/config/laravel.html#getting-started
#

# REQUIREMENTS: Lando 3.0.0-RC.2+ - Tested on 3.0.7

name: $replace-with-a-name$
recipe: laravel

proxy:
  appserver:
    - $replace-with-a-name$.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '7.4'
  via: apache
  cache: redis
  webroot: public
  xdebug: true
  config:
    php: config/php.ini

# Disable key loading - https://docs.lando.dev/config/ssh.html#customizing
keys: false

services:
  appserver:
    ports:
    # A nice handy known-local port  http://localhost:8080
      - '8080:80'

    # Bind my exposes services to all intefaces
    #  - "0.0.0.0::80"

    #
    # PHP / Adding or removing extensions
    # https://docs.devwithlando.io/tutorials/php.html#adding-or-removing-extensions
    #

    #
    # Uncommment this snippet to setup PHP XSL Library for SobiPro
    #
    # build_as_root:
    #   - apt-get update -y
    #   - apt-get install -y libxml2-dev libxslt-dev
    #   - docker-php-ext-install dom xmlrpc xsl

    #
    # Uncommment this snippet to setup Joomla 4 from the GitHub repository
    #
    # build_as_root:
    #   - apt-get update -y
    #   - apt-get install -y re2c libmhash-dev libmcrypt-dev file libgmp-dev
    #   - ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/
    #   - docker-php-ext-configure gmp
    #   - docker-php-ext-install dom xmlrpc gmp

    build_as_root:
      # Apache mod headers
      - a2enmod headers

      # Laravel Instaler
      - composer global require laravel/installer

  database:
    type: mysql:5.7
    # type: mysql:8.0
    # config:
    #   database: config/mysql8.cnf
    portforward: 3306
    creds:
      user: $replace-with-a-name$db
      password: $replace-with-a-name$db
      database: $replace-with-a-name$db

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    portforward: 1025
    hogfrom:
      - appserver

  cache:
    type: redis
    portforward: 6379