##
# package     Extly.VM
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2018 Andrea Gentil - Anibal Sanchez <team@extly.com>
# license     MIT
# link        http://extly.tech
#
# WORKING WITH WORDPRESS - https://docs.devwithlando.io/tutorials/wordpress.html
#

name: wp_tpl
recipe: wordpress

proxy:
  appserver:
    - wp_tpl.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '7.0'
  via: apache
  webroot: www
  xdebug: true

services:
  appserver:
    config:
      conf: config/php.ini
    overrides:
      services:
        # A nice http://localhost:8080
        ports: ['8080:80']

  database:
    type: mysql
    ## portforward: 3306
    creds:
      user: wp_tpldb
      password: wp_tpldb
      database: wp_tpldb

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    ## portforward: 1025
    hogfrom:
      - appserver

tooling:
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell

  wp-install:
    service: appserver
    description: "Command to install WordPress."
    cmd: echo Installing WordPress ...

events:
  post-wp-install:
  - appserver: cd $LANDO_WEBROOT; wp core download
  - appserver: cd $LANDO_WEBROOT; wp core config --dbname=wp_tpldb --dbuser=wp_tpldb --dbpass=wp_tpldb --dbhost=database --dbprefix=wp_
  - appserver: cd $LANDO_WEBROOT; wp core install --url="http://localhost:8080" --title="Blog Title" --admin_user="admin" --admin_password="admin" --admin_email="anibal.sanchez@extly.com"
  - appserver: cd $LANDO_WEBROOT; wp plugin install gutenberg --activate
