##
# package     Extly.VM
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2012-2020 Extly, CB <team@extly.com>
# license     MIT
# link        https://extly.com
#
# WORKING WITH WORDPRESS - https://docs.devwithlando.io/tutorials/wordpress.html
#
# REQUIREMENTS: Lando 3.0.0-RC.2+ - Tested on 3.0.6

name: $replace-with-a-name$
recipe: wordpress

proxy:
  appserver:
    - $replace-with-a-name$.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '7.4'
  via: apache
  webroot: www
  xdebug: true

  # To force Composer v1
  composer_version: '1.10.17'

  config:
    php: config/php.ini

# Disable key loading - https://docs.lando.dev/config/ssh.html#customizing
keys: false

services:
  appserver:
    ports:
    # A nice handy known-local port  http://localhost:8080
      - '8080:80'

    # Bind my exposes services to all intefaces
    #  - "0.0.0.0::80"

  database:
    type: mysql:5.7
    # type: mysql:8.0
    # config:
    #   database: config/mysql8.cnf
    portforward: 3306
    creds:
      user: $replace-with-a-name$db
      password: $replace-with-a-name$db
      database: $replace-with-a-name$db

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  install:
    service: appserver
    description: "Command to install WordPress."
    cmd:
      - echo Installing WordPress ...
      - php config/install_wp.php
