#
# package     Extly.VM
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2018 Andrea Gentil - Anibal Sanchez <team@extly.com>
# license     MIT
# link        http://extly.tech
#
# WORKING WITH JOOMLA - https://docs.devwithlando.io/tutorials/joomla.html
#

# REQUIREMENTS: Lando 3.0.0-RC.2+ - Tested on 3.0.0-RC.17

name: $replace-with-a-name$
recipe: joomla

proxy:
  appserver:
    - $replace-with-a-name$.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '7.3'
  via: apache
  webroot: www
  xdebug: true
  config:
    php: config/php.ini

services:
  appserver:
    ports:
    # A nice handy known-local port  http://localhost:8080
      - '8080:80'

    #
    # PHP / Adding or removing extensions
    # https://docs.devwithlando.io/tutorials/php.html#adding-or-removing-extensions
    #

    #
    # Uncommment this snippet to setup PHP XSL Library for SobiPro
    #
    # build_as_root:
    #   - apt-get update -y
    #   - apt-get install -y libxml2-dev libxslt-dev
    #   - docker-php-ext-install dom xmlrpc xsl

    #
    # Uncommment this snippet to setup Joomla 4 from the GitHub repository
    #
    # build_as_root:
    #   - apt-get update -y
    #   - apt-get install -y re2c libmhash-dev libmcrypt-dev file libgmp-dev
    #   - ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/
    #   - docker-php-ext-configure gmp
    #   - docker-php-ext-install dom xmlrpc gmp

  database:
    type: mysql
    portforward: 3306
    creds:
      user: $replace-with-a-name$db
      password: $replace-with-a-name$db
      database: $replace-with-a-name$db

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    portforward: 1025
    hogfrom:
      - appserver

  # node:
  #   type: node
  #   globals:
  #     gulp-cli: latest

tooling:
  # Tooling Example
  # https://github.com/lando/lando/tree/master/examples/tooling

  # USING SCRIPTY THINGS
  # https://docs.devwithlando.io/config/services.html#using-scripty-things

  install:
    service: appserver
    description: 'Command to install Joomla 3.'
    cmd:
      - echo Installing Joomla ...
      - curl -L https://downloads.joomla.org/cms/joomla3/3-9-12/Joomla_3-9-12-Stable-Full_Package.tar.gz?format=gz |
        tar zxv -C $LANDO_WEBROOT

  install-j4:
    service: appserver
    description: 'Command to install Joomla 4.'
    cmd:
      - echo Installing Joomla 4 ...
      - curl -L https://github.com/joomla/joomla-cms/releases/download/4.0.0-alpha11/Joomla_4.0.0-alpha11-Alpha-Full_Package.tar.gz |
        tar zxv -C $LANDO_WEBROOT

  install-extension:
    service: appserver
    description: 'Command to install an extension (Thanks to Akeeba https://github.com/akeeba/vagrant/blob/master/assets/joomla/install-joomla-extension.php).'
    cmd:
      - echo Installing the extension ...
      - cp $LANDO_MOUNT/config/install-joomla-extension.php $LANDO_WEBROOT/cli &&
        php $LANDO_WEBROOT/cli/install-joomla-extension.php --package="$LANDO_MOUNT/www/tmp/the-extension.gz" 2>/dev/null &&
        rm $LANDO_WEBROOT/cli/install-joomla-extension.php

  install-patchtester:
    service: appserver
    description: 'Command to install the Joomla Patch Tester.'
    cmd:
      - echo Installing the Patch Tester ...
      - curl -L https://github.com/joomla-extensions/patchtester/releases/download/3.0.0-beta4/com_patchtester.tar.gz > "$LANDO_WEBROOT/tmp/com_patchtester.tar.gz"
      - cp "$LANDO_MOUNT/config/install-joomla-extension.php" "$LANDO_WEBROOT/cli" &&
        php "$LANDO_WEBROOT/cli/install-joomla-extension.php" --package="$LANDO_WEBROOT/tmp/com_patchtester.tar.gz" 2>/dev/null &&
        rm "$LANDO_WEBROOT/cli/install-joomla-extension.php"

  dev-config:
    service: appserver
    description: 'Apply my default configuration for JDevelopment'
    cmd:
      - echo Configuring my defaults in configuration.php for JDevelopment…
      - test -e $LANDO_MOUNT/www/configuration.php &&
        sh $LANDO_MOUNT/config/dev-configuration.sh

  kick-restore:
    service: appserver
    description: 'Restore an Akeeba .jpa backup with Kickstart'
    cmd:
      - echo Restoring Akeeba .jpa backup …
      - cd $LANDO_WEBROOT &&
        wget -O kickstart-core-6-0-1-zip.zip "https://www.akeebabackup.com/download/akeeba-kickstart/6-0-1/kickstart-core-6-0-1-zip.zip" &&
        unzip kickstart-core-6-0-1-zip.zip kickstart.php &&
        php kickstart.php *.jpa &&
        rm kickstart.*

  unite-restore:
    service: appserver
    description: 'Full restore of an Akeeba .jpa backup with Unite'
    cmd:
      - echo Restoring Akeeba .jpa backup …
      - test -e $LANDO_MOUNT/config/joomla-unite_tpl.xml &&
        sh $LANDO_MOUNT/config/unite-setup.sh *.jpa $LANDO_APP_NAME $LANDO_WEBROOT &&
        sh $LANDO_MOUNT/config/unite-setup-db.sh $replace-with-a-name$db $replace-with-a-name$db $replace-with-a-name$db &&
        cp /lando/unite.phar $LANDO_MOUNT/www &&
        cd $LANDO_MOUNT/www; php unite.phar joomla-unite.xml &&
        test -e $LANDO_MOUNT/www/configuration.php &&
        sh $LANDO_MOUNT/config/dev-configuration.sh &&
        rm $LANDO_MOUNT/www/unite.phar &&
        rm $LANDO_MOUNT/www/joomla-unite.xml
  # npm:
  #   service: node
  # node:
  #   service: node
  # gulp:
  #   service: node
  # yarn:
  #   service: node
