##
# package     Extly.VM
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2018 Andrea Gentil - Anibal Sanchez <team@extly.com>
# license     MIT
# link        http://extly.tech
#
# WORKING WITH JOOMLA - https://docs.devwithlando.io/tutorials/joomla.html
#

name: $replace-with-a-name$
recipe: joomla

proxy:
  appserver:
    - $replace-with-a-name$.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '7.1'
  via: apache
  webroot: www
  xdebug: true

services:
  appserver:
    config:
      conf: config/php.ini
    overrides:
      services:
        # A nice http://localhost:8080
        ports: ['8080:80']

  database:
    type: mysql
    ## portforward: 3306
    creds:
      user: $replace-with-a-name$db
      password: $replace-with-a-name$db
      database: $replace-with-a-name$db
    # overrides:
    #   services:
    #     image: 'mysql:5.5'

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    ## portforward: 1025
    hogfrom:
      - appserver

tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver

  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell

  install:
    service: appserver
    description: "Command to install Joomla."
    cmd: echo Installing Joomla ...

  install-j4:
    service: appserver
    description: "Command to install Joomla 4."
    cmd: echo Installing Joomla 4 ...

  dev-config:
    service: appserver
    description: "Apply my default configuration for JDevelopment"
    cmd: echo Configuring my defaults in configuration.php for JDevelopment…

  kick-restore:
    service: appserver
    description: "Restore an Akeeba .jpa backup"
    cmd: echo Restoring Akeeba .jpa backup …

  unite-restore:
    service: appserver
    description: "Full restore of an Akeeba .jpa backup with Unite"
    cmd: echo Restoring Akeeba .jpa backup …

events:
  post-install:
    - appserver: curl -L https://downloads.joomla.org/cms/joomla3/3-8-8/Joomla_3-8-8-Stable-Full_Package.tar.gz | tar zxv -C $LANDO_WEBROOT

  post-install-j4:
    - appserver: curl -L https://github.com/joomla/joomla-cms/releases/download/4.0.0-alpha3/Joomla_4.0.0-alpha3-Alpha-Full_Package.tar.gz | tar zxv -C $LANDO_WEBROOT

  post-dev-config:
      - appserver: test -e $LANDO_MOUNT/www/configuration.php && sh $LANDO_MOUNT/config/dev-configuration.sh

  post-kick-restore:
    - appserver: cd $LANDO_WEBROOT; wget -O kickstart.zip https://www.akeebabackup.com/download/akeeba-kickstart/5-4-2/kickstart-core-5-4-2-zip.zip
    - appserver: cd $LANDO_WEBROOT; unzip kickstart.zip kickstart.php
    - appserver: cd $LANDO_WEBROOT; php kickstart.php *.jpa
    - appserver: cd $LANDO_WEBROOT; rm kickstart.*
    - appserver: cd $LANDO_WEBROOT; rm .htaccess

  post-unite-restore:
    - appserver: test -e $LANDO_MOUNT/config/joomla-unite_tpl.xml && sh $LANDO_MOUNT/config/unite-setup.sh *.jpa $LANDO_APP_NAME $LANDO_WEBROOT
    - database: test -e $LANDO_MOUNT/www/joomla-unite.tmp && sh $LANDO_MOUNT/config/unite-setup-db.sh $MYSQL_DATABASE $MYSQL_USER $MYSQL_PASSWORD
    - appserver: cp /lando/unite.phar $LANDO_MOUNT/www
    - appserver: cd $LANDO_MOUNT/www; php unite.phar joomla-unite.xml
    - appserver: test -e $LANDO_MOUNT/www/configuration.php && sh $LANDO_MOUNT/config/dev-configuration.sh
    - appserver: rm $LANDO_MOUNT/www/unite.phar
    - appserver: rm $LANDO_MOUNT/www/joomla-unite.xml