##
# package     Extly.VM
# subpackage  Lando Boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2007 - 2017 Extly, CB. All rights reserved.
# license     http://www.gnu.org/licenses/gpl-3.0.html GNU/GPL
# link        http://extly.tech
#
# WORKING WITH JOOMLA - https://docs.devwithlando.io/tutorials/joomla.html
#

name: joomla_tpl
recipe: joomla

proxy:
  appserver:
    - joomla_tpl.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '7.1'
  via: apache
  webroot: www
  xdebug: true

services:
  appserver:
    config:
      conf: config/php.ini
    overrides:
      services:
        # A nice http://localhost:8080
        ports: ['8080:80']

  database:
    type: mysql
    ## portforward: 3306
    creds:
      user: joomla_tpldb
      password: joomla_tpldb
      database: joomla_tpldb

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    ## portforward: 1025
    hogfrom:
      - appserver

tooling:
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell

  j-install:
    service: appserver
    description: "Command to install Joomla."
    cmd: echo Installing Joomla ...

  j-dev:
    service: appserver
    description: "Apply my default configuration for JDevelopment"
    cmd: echo Configuring my defaults in configuration.php for JDevelopment…

events:
  post-j-install:
    - appserver: curl -L https://downloads.joomla.org/cms/joomla3/3-8-7/Joomla_3-8-7-Stable-Full_Package.tar.gz | tar zxv -C $LANDO_WEBROOT

  post-j-dev:
      - appserver: test -e $LANDO_MOUNT/www/configuration.php && sh $LANDO_MOUNT/config/j-dev.sh